
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/mingw64/bin/clang 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.7.2+d6990bcfa for .NET Framework
      Build started 1/30/2024 6:01:06 PM.
      
      Project "C:\\C++\\Chess_2\\builddir\\meson-private\\cmake_animationwindow\\CMakeFiles\\3.28.0-rc1\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        Touching "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\C++\\Chess_2\\builddir\\meson-private\\cmake_animationwindow\\CMakeFiles\\3.28.0-rc1\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Done Building Project "C:\\C++\\Chess_2\\builddir\\meson-private\\cmake_animationwindow\\CMakeFiles\\3.28.0-rc1\\CompilerIdC\\CompilerIdC.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:01.71
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/C++/Chess_2/builddir/meson-private/cmake_animationwindow/CMakeFiles/3.28.0-rc1/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/mingw64/bin/clang++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.7.2+d6990bcfa for .NET Framework
      Build started 1/30/2024 6:01:08 PM.
      
      Project "C:\\C++\\Chess_2\\builddir\\meson-private\\cmake_animationwindow\\CMakeFiles\\3.28.0-rc1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        Touching "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\C++\\Chess_2\\builddir\\meson-private\\cmake_animationwindow\\CMakeFiles\\3.28.0-rc1\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Done Building Project "C:\\C++\\Chess_2\\builddir\\meson-private\\cmake_animationwindow\\CMakeFiles\\3.28.0-rc1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:01.44
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/C++/Chess_2/builddir/meson-private/cmake_animationwindow/CMakeFiles/3.28.0-rc1/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/C++/Chess_2/builddir/meson-private/cmake_animationwindow/CMakeFiles/CMakeScratch/TryCompile-y2ufa1"
      binary: "C:/C++/Chess_2/builddir/meson-private/cmake_animationwindow/CMakeFiles/CMakeScratch/TryCompile-y2ufa1"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/C++/Chess_2/builddir/meson-private/cmake_animationwindow/CMakeFiles/CMakeScratch/TryCompile-y2ufa1'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_3074a.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.7.2+d6990bcfa for .NET Framework
        Build started 1/30/2024 6:01:10 PM.
        
        Project "C:\\C++\\Chess_2\\builddir\\meson-private\\cmake_animationwindow\\CMakeFiles\\CMakeScratch\\TryCompile-y2ufa1\\cmTC_3074a.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_3074a.dir\\Debug\\".
          Creating directory "C:\\C++\\Chess_2\\builddir\\meson-private\\cmake_animationwindow\\CMakeFiles\\CMakeScratch\\TryCompile-y2ufa1\\Debug\\".
          Creating directory "cmTC_3074a.dir\\Debug\\cmTC_3074a.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_3074a.dir\\Debug\\cmTC_3074a.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
          Touching "cmTC_3074a.dir\\Debug\\cmTC_3074a.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_3074a.dir\\Debug\\\\" /Fd"cmTC_3074a.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32824 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          CMakeCCompilerABI.c
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_3074a.dir\\Debug\\\\" /Fd"cmTC_3074a.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\C++\\Chess_2\\builddir\\meson-private\\cmake_animationwindow\\CMakeFiles\\CMakeScratch\\TryCompile-y2ufa1\\Debug\\cmTC_3074a.exe" /INCREMENTAL /ILK:"cmTC_3074a.dir\\Debug\\cmTC_3074a.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/C++/Chess_2/builddir/meson-private/cmake_animationwindow/CMakeFiles/CMakeScratch/TryCompile-y2ufa1/Debug/cmTC_3074a.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/C++/Chess_2/builddir/meson-private/cmake_animationwindow/CMakeFiles/CMakeScratch/TryCompile-y2ufa1/Debug/cmTC_3074a.lib" /MACHINE:X64  /machine:x64 cmTC_3074a.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_3074a.vcxproj -> C:\\C++\\Chess_2\\builddir\\meson-private\\cmake_animationwindow\\CMakeFiles\\CMakeScratch\\TryCompile-y2ufa1\\Debug\\cmTC_3074a.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_3074a.dir\\Debug\\cmTC_3074a.tlog\\unsuccessfulbuild".
          Touching "cmTC_3074a.dir\\Debug\\cmTC_3074a.tlog\\cmTC_3074a.lastbuildstate".
        Done Building Project "C:\\C++\\Chess_2\\builddir\\meson-private\\cmake_animationwindow\\CMakeFiles\\CMakeScratch\\TryCompile-y2ufa1\\cmTC_3074a.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:01.41
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/C++/Chess_2/builddir/meson-private/cmake_animationwindow/CMakeFiles/CMakeScratch/TryCompile-tmf5jv"
      binary: "C:/C++/Chess_2/builddir/meson-private/cmake_animationwindow/CMakeFiles/CMakeScratch/TryCompile-tmf5jv"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/C++/Chess_2/builddir/meson-private/cmake_animationwindow/CMakeFiles/CMakeScratch/TryCompile-tmf5jv'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_d7987.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.7.2+d6990bcfa for .NET Framework
        Build started 1/30/2024 6:01:12 PM.
        
        Project "C:\\C++\\Chess_2\\builddir\\meson-private\\cmake_animationwindow\\CMakeFiles\\CMakeScratch\\TryCompile-tmf5jv\\cmTC_d7987.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_d7987.dir\\Debug\\".
          Creating directory "C:\\C++\\Chess_2\\builddir\\meson-private\\cmake_animationwindow\\CMakeFiles\\CMakeScratch\\TryCompile-tmf5jv\\Debug\\".
          Creating directory "cmTC_d7987.dir\\Debug\\cmTC_d7987.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_d7987.dir\\Debug\\cmTC_d7987.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
          Touching "cmTC_d7987.dir\\Debug\\cmTC_d7987.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_d7987.dir\\Debug\\\\" /Fd"cmTC_d7987.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32824 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_d7987.dir\\Debug\\\\" /Fd"cmTC_d7987.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\C++\\Chess_2\\builddir\\meson-private\\cmake_animationwindow\\CMakeFiles\\CMakeScratch\\TryCompile-tmf5jv\\Debug\\cmTC_d7987.exe" /INCREMENTAL /ILK:"cmTC_d7987.dir\\Debug\\cmTC_d7987.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/C++/Chess_2/builddir/meson-private/cmake_animationwindow/CMakeFiles/CMakeScratch/TryCompile-tmf5jv/Debug/cmTC_d7987.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/C++/Chess_2/builddir/meson-private/cmake_animationwindow/CMakeFiles/CMakeScratch/TryCompile-tmf5jv/Debug/cmTC_d7987.lib" /MACHINE:X64  /machine:x64 cmTC_d7987.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_d7987.vcxproj -> C:\\C++\\Chess_2\\builddir\\meson-private\\cmake_animationwindow\\CMakeFiles\\CMakeScratch\\TryCompile-tmf5jv\\Debug\\cmTC_d7987.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_d7987.dir\\Debug\\cmTC_d7987.tlog\\unsuccessfulbuild".
          Touching "cmTC_d7987.dir\\Debug\\cmTC_d7987.tlog\\cmTC_d7987.lastbuildstate".
        Done Building Project "C:\\C++\\Chess_2\\builddir\\meson-private\\cmake_animationwindow\\CMakeFiles\\CMakeScratch\\TryCompile-tmf5jv\\cmTC_d7987.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:01.36
        
      exitCode: 0
...
